# fly.toml app configuration file generated for bites-journey-2 on 2023-11-02T22:37:05+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bites-journey-2"
primary_region = "sin"

[build]

[http_service]
  internal_port = 9000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]